#Shortcuts

#Dirs
abbr -a -g  cdcache "cd /home/psihoz/.cache && ls -a"
abbr -a -g  cdconf "cd /home/psihoz/.config && ls -a"
abbr -a -g  cdshare "cd /home/psihoz/.local/share && ls -a"
abbr -a -g  cdmnt "cd /mnt && ls -a"
abbr -a -g  cdscr "cd /home/psihoz/.local/bin/myScripts && ls -a" 
abbr -a -g  cdsrc "cd /home/psihoz/.local/src && ls -a" 
abbr -a -g  cddiary "cd /home/psihoz/vimwiki/diary && ls -a"
abbr -a -g  cdshell "cd /home/psihoz/.config/shell && ls -a"
abbr -a -g  cdwm "cd /home/psihoz/.local/src/dwm-flexipatch-finalized && ls -a"
abbr -a -g  cdwmb "cd /home/psihoz/.local/src/dwmblocks && ls -a"
abbr -a -g  cdst "cd /home/psihoz/.local/src/st-flexipatch && ls -a"

#Files
abbr -a -g  cfbf "$EDITOR /home/psihoz/.config/shell/bm-files" 
abbr -a -g  cfbd "$EDITOR /home/psihoz/.config/shell/bm-dirs"
abbr -a -g  cfx "$EDITOR /home/psihoz/.config/x11/xresources"
abbr -a -g  cfxprofile "$EDITOR /home/psihoz/.config/x11/xprofile"
abbr -a -g  cfdunst "$EDITOR /home/psihoz/.config/dunst/dunstrc"
abbr -a -g  cfv "$EDITOR /home/psihoz/.config/nvim/init.vim"
abbr -a -g  cfdb "$EDITOR ~/.local/src/dwmblocks/config.h"
abbr -a -g  cfst "$EDITOR ~/.local/src/st-flexipatch/config.h"
abbr -a -g  cfd "$EDITOR ~/.local/src/dwm-flexipatch-finalized/config.h"
abbr -a -g  cfdh "$EDITOR ~/.local/src/dwm-flexipatch-finalized/hotkeys.c"
abbr -a -g  cfz "$EDITOR /home/psihoz/.config/zsh/.zshrc"
abbr -a -g  cfp "$EDITOR /home/psihoz/.config/shell/profile"
abbr -a -g  cff "$EDITOR $XDG_CONFIG_HOME/fish/config.fish"
abbr -a -g  cfalias "$EDITOR $XDG_CONFIG_HOME/fish/aliasrc.fish"
abbr -a -g  cfshort "$EDITOR $XDG_CONFIG_HOME/fish/shortcutrc.fish"
